name: Subtask
description: Create a subtask for breaking down work items
title: "[SUBTASK] "
labels: ["Subtask"]
body:
  - type: textarea
    attributes:
      label: Task Details
    validations:
      required: true
